// Jenkinsfile for MLBParks
// TODO change 172.30.1.1:5000 to docker-registry.default.svc
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-slave-appdev:latest",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
  ) {
    node('skopeo-pod') {
      echo "GUID: ${GUID}"
      echo "CLUSTER: ${CLUSTER}"

      // Checkout Source Code
      stage('Checkout Source') {
        // should be enough, because we already set the git location in the pipeline definition
        checkout scm
      }

      // setup the nexus_settings so it reflects our GUID and CLUSTER args
      sh "pwd"
      sh "ls"
      sh "cp ./nexus_settings.xml ./MLBParks/"
      sh "sed -i 's/GUID/${GUID}/' ./MLBParks/nexus_settings.xml"
      sh "sed -i 's/CLUSTER/${CLUSTER}/' ./MLBParks/nexus_settings.xml"
      sh "cat ./MLBParks/nexus_settings.xml"

      def mvnCmd = "mvn -s nexus_settings.xml"

      def groupId    = getGroupIdFromPom("./MLBParks/pom.xml")
      def artifactId = getArtifactIdFromPom("./MLBParks/pom.xml")
      def version    = getVersionFromPom("./MLBParks/pom.xml")

      // Set the tag for the development image: version + build number
      def devTag  = "${version}-${BUILD_NUMBER}"
      // Set the tag for the production image: version
      def prodTag = "${version}"

      // Using Maven build the war file
      // Do not run tests in this step
      stage('Build war') {
        dir("MLBParks") {
          sh "${mvnCmd} clean package -DskipTests"
        }
        echo "Building version ${devTag}"
      }

      // Using Maven run the unit tests
      stage('Unit Tests') {
        echo "Running Unit Tests"
        dir("MLBParks") {
          sh "${mvnCmd} test"
        }
      }    
  
      // Code analysis
      stage('Code Analysis') {
        echo "Running Code Analysis"
        dir("MLBParks") {
          sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube.${GUID}-sonarqube.${CLUSTER}:9000/ -Dsonar.projectName=${JOB_BASE_NAME}-${devTag}"      
        }
      }    

      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        echo "Publish to Nexus"
        dir("MLBParks") {
          sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3.${GUID}-nexus.${CLUSTER}:8081/repository/releases"
        }
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image mlbparks:${devTag}"
        // this will simply kick off the build, using the war file we just maven build to target 
        sh "oc start-build mlbparks --follow --from-file=./MLBParks/target/mlbparks.war -n ${GUID}-parks-dev"
        // use Jenkins plug in to tag the image
        openshiftTag alias: 'false', destStream: 'mlbparks', destTag: devTag, destinationNamespace: '${GUID}-parks-dev', namespace: '${GUID}-parks-dev', srcStream: 'mlbparks', srcTag: 'latest', verbose: 'false'
      }

      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"
      
        // We need to update the dc to the new image (needed because it is versioned!)
        sh "oc set image dc/mlbparks mlbparks=docker-registry.default.svc:5000/${GUID}-parks-dev/mlbparks:${devTag} -n ${GUID}-parks-dev"

      // Deploy the development application.
      openshiftDeploy depCfg: 'mlbparks', namespace: '${GUID}-parks-dev', verbose: 'false', waitTime: '20', waitUnit: 'min'
      openshiftVerifyDeployment depCfg: 'mlbparks', namespace: '${GUID}-parks-dev', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: '', waitUnit: 'sec'
      openshiftVerifyService namespace: '${GUID}-parks-dev', svcName: 'mlbparks', verbose: 'false'
    }

  } 
}

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
