// Jenkinsfile for Nationalparks
// TODO unskip tests, set ip back to docker-registry
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "172.30.1.1:5000/${GUID}-jenkins/jenkins-slave-appdev:latest",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
  ) {
    node('skopeo-pod') {
      echo "GUID: ${GUID}"
      echo "CLUSTER: ${CLUSTER}"

      // Checkout Source Code
      stage('Checkout Source') {
        // should be enough, because we already set the git location in the pipeline definition
        checkout scm
      }

      // setup the nexus_settings so it reflects our GUID and CLUSTER args
      sh "pwd"
      sh "ls"
      sh "cp ./nexus_settings.xml ./Nationalparks/"
      sh "sed -i 's/GUID/${GUID}/' ./Nationalparks/nexus_settings.xml"
      sh "sed -i 's/CLUSTER/${CLUSTER}/' ./Nationalparks/nexus_settings.xml"
      sh "cat ./Nationalparks/nexus_settings.xml"

      def mvnCmd = "mvn -s nexus_settings.xml"

      def groupId    = getGroupIdFromPom("./Nationalparks/pom.xml")
      def artifactId = getArtifactIdFromPom("./Nationalparks/pom.xml")
      def version    = getVersionFromPom("./Nationalparks/pom.xml")

      // Set the tag for the development image: version + build number
      def devTag  = "${version}-${BUILD_NUMBER}"
      // Set the tag for the production image: version
      def prodTag = "${version}"

      // Using Maven build the jar file
      // Do not run tests in this step
      stage('Build JAR') {
        dir("Nationalparks") {
          sh "${mvnCmd} clean package -DskipTests"
        }
        echo "Building version ${devTag}"
      }

      // Using Maven run the unit tests
      stage('Unit Tests') {
        echo "Running Unit Tests"
        dir("Nationalparks") {
         sh "${mvnCmd} test"
        }
      }    
  
      // Code analysis
      stage('Code Analysis') {
        // echo "Running Code Analysis"
        // dir("Nationalparks") {
        //  sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube.${GUID}-sonarqube.${CLUSTER}:9000/ -Dsonar.projectName=${JOB_BASE_NAME}-${devTag}"      
        // }
      }    

      // Publish the built jar file to Nexus
      stage('Publish to Nexus') {
        // echo "Publish to Nexus"
        // dir("Nationalparks") {
        //   sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3.${GUID}-nexus.${CLUSTER}:8081/repository/releases"
        // }
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image nationalparks:${devTag}"
        // this will simply kick off the build, using the jar file we just maven build to target 
        sh "oc start-build nationalparks --follow --from-file=./Nationalparks/target/nationalparks.jar -n ${GUID}-parks-dev"
        // use Jenkins plug in to tag the image
        openshiftTag alias: 'false', destStream: 'nationalparks', destTag: devTag, destinationNamespace: '${GUID}-parks-dev', namespace: '${GUID}-parks-dev', srcStream: 'nationalparks', srcTag: 'latest', verbose: 'false'
      }

      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"
        // We need to update the dc to the new image (needed because it is versioned!)
        // sh "oc set image dc/nationalparks nationalparks=docker-registry.default.svc:5000/${GUID}-parks-dev/nationalparks:${devTag} -n ${GUID}-parks-dev"
        // Because above 'set image' was not working (it triggered a deploy but with same image :( we're using lines below instead)
        sh "oc set triggers dc/nationalparks --remove-all -n ${GUID}-parks-dev" // remove existing triggers, then add a new one
        sh "oc set triggers dc/nationalparks --from-image=nationalparks:${devTag} --containers=nationalparks -n ${GUID}-parks-dev" 
        // Deploy the development application.
        openshiftDeploy depCfg: 'nationalparks', namespace: '${GUID}-parks-dev', verbose: 'false', waitTime: '20', waitUnit: 'min'
        openshiftVerifyDeployment depCfg: 'nationalparks', namespace: '${GUID}-parks-dev', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyService namespace: '${GUID}-parks-dev', svcName: 'nationalparks', verbose: 'false'
      }

      stage('Blue/Green Production Deployment') {
        activeApp = sh(returnStdout: true, script: "oc get route nationalparks -n ${GUID}-parks-prod -o jsonpath='{ .spec.to.name }'").trim()
        if (activeApp == "nationalparks-green") {
          destApp = "nationalparks-blue"
        }
        echo "Active Application:      " + activeApp
        echo "Destination Application: " + destApp

        // Update the Image on the Production Deployment Config
        // TODO do not use IP
        sh "oc set image dc/${destApp} ${destApp}=172.30.1.1:5000/${GUID}-parks-dev/nationalparks:${prodTag} -n ${GUID}-parks-prod"

        // Deploy the inactive application.
        openshiftDeploy depCfg: destApp, namespace: '${GUID}-parks-prod', verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment depCfg: destApp, namespace: '${GUID}-parks-prod', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'
        openshiftVerifyService namespace: '${GUID}-parks-prod', svcName: destApp, verbose: 'false'
      }
  } 
}

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
