apiVersion: v1
kind: BuildConfig
metadata:
  name: "mlbparks-pipeline"
spec:
  source:
    contextDir: MLBParks
    type: Git
    git:
      uri: ${REPO}
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
       env:
         - name: GUID
           value: ${GUID}
         - name: CLUSTER
           value: ${CLUSTER}
parameters:
- description: The GUID  
  displayName: GUID
  name: GUID
  value: xyz
- description: The repository that holds the source
  displayName: REPO
  name: REPO
  value: "http://github.com/etc"
- description: The cluster
  displayName: CLUSTER
  name: CLUSTER
  value: "http://some-openshift-cluster"
